CC = gcc
LD = gcc
AR = ar
EXECS = fc_open
LARGE_FILE_FLAGS = -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64

CFLAGS = -g -O2 -W -Wall -iquote ../include -D_REENTRANT $(LARGE_FILE_FLAGS)
LDFLAGS = -lsgutils2 -L . -lscsifile
MYLIB = libscsifile.a
LIBOBJS = ody_scsi_file.o ody_scsi_ptcmd.linux.o
all: $(EXECS) $(MYLIB)
clean:
	/bin/rm -f *.o $(EXECS)  core
$(MYLIB): $(LIBOBJS)
	$(AR) -rv $@ $(LIBOBJS)
fc_open: fc_open_test.o $(MYLIB)
	$(LD) -o $@ $(LDFLAGS) $^
.c.o:
	$(CC) $(CFLAGS) -c $<
